[DockerLogInput]
decoder = "systemzoo_decoder"

[systemzoo_decoder]
type = "SandboxDecoder"
filename = "lua_decoders/systemzoo.lua"

[systemzoo_decoder.config]
type = "systemzoo.log"

[systemzoo_encoder]                                                                    
type = "SandboxEncoder"                                                                
filename = "lua_encoders/systemzoo_encoder.lua"                                         
ticker_interval = 1                                                                    
preserve_data = true                                                                   
                                                                                       
[systemzoo_encoder.config]                                                             
type = "systemzoo.log"
